#!/usr/bin/perl
#############################################################################
#
# rx_* dispatcher and handlers for VFU File Manager
# (c) Vladi Belperchinov-Shabanski "Cade" 2002 
# <cade@biscom.net> <cade.datamax.bg> http://cade.webbg.com
# $Id: rx_ftp,v 1.2 2002/11/06 20:24:26 cade Exp $
#
# usage:
#   rx_* l archive directory   # list archive directory 
#   rx_* v archive             # list entire archive
#   rx_* x archive files...    # extract one file
#   rx_* x archive @listfile   # extract list of files
#
#############################################################################

$command = shift @ARGV;
$archive = shift @ARGV;

if ( $command eq "v" || $command eq "V" )
   {
   $dir = shift @ARGV;
   if ( $dir ) { $dir .= "/" unless $dir =~ /\/$/; }
 
   open( i, "ftparc -l -r -q $archive      |" ) if $command eq "V";
   open( i, "ftparc -l    -q $archive $dir |" ) if $command eq "v";

   if ( $command eq "V" )
     {
     $rex = "(.[\\-rwxsStT]{9})\\s+\\S+\\s+\\S+\\s+\\S+\\s+(\\d+)\\s+............\\s+(\\S+[^\\/])";
     }
   else
     {
     $rex = "(.[\\-rwxsStT]{9})\\s+\\S+\\s+\\S+\\s+\\S+\\s+(\\d+)\\s+............\\s+(\\S+)";
     }

   $count = 0;
   while(<i>)
      {
      chop;
      s/\s+->\s+\S+$//;
      if (/^$rex$/)
        {
        print "NAME:$3\nSIZE:$2\nMODE:$1\n\n";
        $count++;
        }
      }

   close( i );
   }
elsif ( $command eq "x" )
  {
  system( "ftparc -x -q $archive $ARGV[0]" );
  }
else
  {
  die $0 . ": wrong command.\n";
  }

