#!/usr/bin/perl
#############################################################################
#
# rx_* dispatcher and handlers for VFU File Manager
# (c) Vladi Belperchinov-Shabanski "Cade" 2002 
# <cade@biscom.net> <cade.datamax.bg> http://cade.webbg.com
# $Id: rx_ftp,v 1.3 2002/11/07 23:22:21 cade Exp $
#
# usage:
#   rx_* l archive directory   # list archive directory 
#   rx_* v archive             # list entire archive
#   rx_* x archive files...    # extract one file
#   rx_* x archive @listfile   # extract list of files
#
#############################################################################
use Net::FTP;
use strict;

my $cmd = lc shift @ARGV;
my $archive = shift @ARGV;
my $cache = "/tmp/$archive.rx.cache";
$cache =~ s/^(\/tmp\/)(.+)\/([^\/]+)$/$1$3/;

my $i;
open $i, $archive;
my $host = <$i>;
my $user = <$i>;
my $pass = <$i>;
close $i;
chop($host);
chop($user);
chop($pass);

my $ftp = Net::FTP->new( $host ) or die "$0: cannot connect to $host\n";

$user = 'anonymous' if $user eq '-';
$pass = "$ENV{USER}\@$ENV{HOSTNAME}" if $pass eq '-';
$ftp->login( $user, $pass ) or die "$0: cannot login as $user into $host\n";

if ( $cmd eq "l" || $cmd eq "v" )
  {
  my $dir = shift @ARGV;
  $ftp->cwd( $dir );
  
  my @list = $ftp->dir();
  for( @list )
    {
    my @D = split /\s+/, $_;
    my $N = pop @D;
    my $M = $D[0];
    my $S = $D[4];
    $N .= '/' if $M =~ /^d/i;
    print "NAME:$N\nSIZE:$S\nMODE:$M\n\n";
    }
  }
elsif ( $cmd eq "x" )
  {
  my @list;
  if ( $ARGV[0] =~ /^\@(.+)$/ )
    {
    my $i;
    open $i, $1;
    @list = <$i>;
    close $i;
    chop( @list );
    }
  else
    {
    @list = @ARGV;
    }
  for( @ARGV )  
    {
    /^\/(.+\/)?([^\/]+)$/ and mkdir $1;
    $ftp->get( $_, $1 . $2 );
    }
  }
else
  {
  die $0 . ": wrong command.\n";
  }



=pod
$command = shift @ARGV;
$archive = shift @ARGV;

if ( $command eq "v" || $command eq "V" )
   {
   $dir = shift @ARGV;
   if ( $dir ) { $dir .= "/" unless $dir =~ /\/$/; }
 
   open( i, "ftparc -l -r -q $archive      |" ) if $command eq "V";
   open( i, "ftparc -l    -q $archive $dir |" ) if $command eq "v";

   if ( $command eq "V" )
     {
     $rex = "(.[\\-rwxsStT]{9})\\s+\\S+\\s+\\S+\\s+\\S+\\s+(\\d+)\\s+............\\s+(\\S+[^\\/])";
     }
   else
     {
     $rex = "(.[\\-rwxsStT]{9})\\s+\\S+\\s+\\S+\\s+\\S+\\s+(\\d+)\\s+............\\s+(\\S+)";
     }

   $count = 0;
   while(<i>)
      {
      chop;
      s/\s+->\s+\S+$//;
      if (/^$rex$/)
        {
        print "NAME:$3\nSIZE:$2\nMODE:$1\n\n";
        $count++;
        }
      }

   close( i );
   }
elsif ( $command eq "x" )
  {
  system( "ftparc -x -q $archive $ARGV[0]" );
  }
else
  {
  die $0 . ": wrong command.\n";
  }
=cut
